const baoCaoTonData = [
    {
        id: 'S001',
        name: 'Book 1',
        author: 'Author E',
        category: 'Cơ sở dữ liệu',
        startStock: 56,
        change: 22,
        endStock: 78,
        month: 11,
        year: 2025
    },
    {
        id: 'S002',
        name: 'Book 2',
        author: 'Author C',
        category: 'Lập trình',
        startStock: 89,
        change: 11,
        endStock: 100,
        month: 5,
        year: 2025
    },
    {
        id: 'S003',
        name: 'Book 3',
        author: 'Author B',
        category: 'Lập trình',
        startStock: 29,
        change: -5,
        endStock: 24,
        month: 6,
        year: 2024
    },
    {
        id: 'S004',
        name: 'Book 4',
        author: 'Author A',
        category: 'Hệ thống thông tin',
        startStock: 44,
        change: 19,
        endStock: 63,
        month: 7,
        year: 2025
    },
    {
        id: 'S005',
        name: 'Book 5',
        author: 'Author D',
        category: 'Cơ sở dữ liệu',
        startStock: 45,
        change: -8,
        endStock: 37,
        month: 7,
        year: 2025
    },
    {
        id: 'S006',
        name: 'Book 6',
        author: 'Author A',
        category: 'Cơ sở dữ liệu',
        startStock: 27,
        change: 35,
        endStock: 62,
        month: 9,
        year: 2025
    },
    {
        id: 'S007',
        name: 'Book 7',
        author: 'Author C',
        category: 'Cơ sở dữ liệu',
        startStock: 65,
        change: -30,
        endStock: 35,
        month: 8,
        year: 2024
    },
    {
        id: 'S008',
        name: 'Book 8',
        author: 'Author A',
        category: 'Lập trình',
        startStock: 77,
        change: 23,
        endStock: 100,
        month: 10,
        year: 2024
    },
    {
        id: 'S009',
        name: 'Book 9',
        author: 'Author B',
        category: 'Cơ sở dữ liệu',
        startStock: 37,
        change: -3,
        endStock: 34,
        month: 8,
        year: 2025
    },
    {
        id: 'S010',
        name: 'Book 10',
        author: 'Author C',
        category: 'Khoa học máy tính',
        startStock: 45,
        change: 41,
        endStock: 86,
        month: 8,
        year: 2024
    },
    {
        id: 'S011',
        name: 'Book 11',
        author: 'Author D',
        category: 'Lập trình',
        startStock: 40,
        change: 10,
        endStock: 50,
        month: 3,
        year: 2025
    },
    {
        id: 'S012',
        name: 'Book 12',
        author: 'Author B',
        category: 'Lập trình',
        startStock: 62,
        change: 20,
        endStock: 82,
        month: 12,
        year: 2024
    },
    {
        id: 'S013',
        name: 'Book 13',
        author: 'Author E',
        category: 'Khoa học máy tính',
        startStock: 30,
        change: 15,
        endStock: 45,
        month: 6,
        year: 2025
    },
    {
        id: 'S014',
        name: 'Book 14',
        author: 'Author A',
        category: 'Lập trình',
        startStock: 54,
        change: 19,
        endStock: 73,
        month: 11,
        year: 2024
    },
    {
        id: 'S015',
        name: 'Book 15',
        author: 'Author C',
        category: 'Khoa học máy tính',
        startStock: 88,
        change: 7,
        endStock: 95,
        month: 5,
        year: 2025
    },
    {
        id: 'S016',
        name: 'Book 16',
        author: 'Author D',
        category: 'Cơ sở dữ liệu',
        startStock: 60,
        change: -15,
        endStock: 45,
        month: 10,
        year: 2024
    },
    {
        id: 'S017',
        name: 'Book 17',
        author: 'Author E',
        category: 'Lập trình',
        startStock: 70,
        change: 20,
        endStock: 90,
        month: 1,
        year: 2025
    },
    {
        id: 'S018',
        name: 'Book 18',
        author: 'Author C',
        category: 'Khoa học máy tính',
        startStock: 60,
        change: -10,
        endStock: 50,
        month: 8,
        year: 2025
    },
    {
        id: 'S019',
        name: 'Book 19',
        author: 'Author A',
        category: 'Lập trình',
        startStock: 45,
        change: 15,
        endStock: 60,
        month: 3,
        year: 2024
    },
    {
        id: 'S020',
        name: 'Book 20',
        author: 'Author B',
        category: 'Khoa học máy tính',
        startStock: 90,
        change: -5,
        endStock: 85,
        month: 6,
        year: 2024
    },
    {
        id: 'S021',
        name: 'Book 21',
        author: 'Author A',
        category: 'Lập trình',
        startStock: 40,
        change: 15,
        endStock: 55,
        month: 1,
        year: 2025
    },
    {
        id: 'S022',
        name: 'Book 22',
        author: 'Author B',
        category: 'Khoa học máy tính',
        startStock: 65,
        change: 10,
        endStock: 75,
        month: 1,
        year: 2025
    },
    {
        id: 'S023',
        name: 'Book 23',
        author: 'Author C',
        category: 'Lập trình',
        startStock: 50,
        change: 30,
        endStock: 80,
        month: 1,
        year: 2025
    },
    {
        id: 'S024',
        name: 'Book 24',
        author: 'Author D',
        category: 'Khoa học máy tính',
        startStock: 60,
        change: 5,
        endStock: 65,
        month: 1,
        year: 2025
    },
    {
        id: 'S025',
        name: 'Book 25',
        author: 'Author E',
        category: 'Lập trình',
        startStock: 45,
        change: 20,
        endStock: 65,
        month: 1,
        year: 2025
    },
    {
        id: 'S026',
        name: 'Book 26',
        author: 'Author A',
        category: 'Cơ sở dữ liệu',
        startStock: 40,
        change: 25,
        endStock: 65,
        month: 1,
        year: 2025
    },
    {
        id: 'S027',
        name: 'Book 27',
        author: 'Author C',
        category: 'Lập trình',
        startStock: 80,
        change: -10,
        endStock: 70,
        month: 1,
        year: 2025
    },
    {
        id: 'S028',
        name: 'Book 28',
        author: 'Author B',
        category: 'Khoa học máy tính',
        startStock: 90,
        change: 15,
        endStock: 105,
        month: 1,
        year: 2025
    },
    {
        id: 'S029',
        name: 'Book 29',
        author: 'Author D',
        category: 'Lập trình',
        startStock: 55,
        change: 25,
        endStock: 80,
        month: 1,
        year: 2025
    },
    {
        id: 'S030',
        name: 'Book 30',
        author: 'Author E',
        category: 'Khoa học máy tính',
        startStock: 70,
        change: -5,
        endStock: 65,
        month: 1,
        year: 2025
    },
    {
        id: 'S031',
        name: 'Book 31',
        author: 'Author A',
        category: 'Lập trình',
        startStock: 50,
        change: 20,
        endStock: 70,
        month: 1,
        year: 2025
    },
    {
        id: 'S032',
        name: 'Book 32',
        author: 'Author B',
        category: 'Lập trình',
        startStock: 40,
        change: 15,
        endStock: 55,
        month: 1,
        year: 2025
    },
    {
        id: 'S033',
        name: 'Book 33',
        author: 'Author C',
        category: 'Cơ sở dữ liệu',
        startStock: 60,
        change: -20,
        endStock: 40,
        month: 1,
        year: 2025
    },
    {
        id: 'S034',
        name: 'Book 34',
        author: 'Author D',
        category: 'Khoa học máy tính',
        startStock: 50,
        change: 30,
        endStock: 80,
        month: 1,
        year: 2025
    },
    {
        id: 'S035',
        name: 'Book 35',
        author: 'Author E',
        category: 'Lập trình',
        startStock: 60,
        change: 5,
        endStock: 65,
        month: 1,
        year: 2025
    }
    // Add more records up to S050
    ];
    
    export default baoCaoTonData;
    
